# Generated by Django 2.2.1 on 2019-05-29 22:17

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('queued', 'QUEUED'), ('started', 'STARTED'), ('done', 'DONE')], default='queued', max_length=7)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField()),
                ('job_id', models.UUIDField(blank=True, null=True)),
                ('result', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
