# Generated by Django 2.2.1 on 2019-05-31 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='data',
            field=models.TextField(),
        ),
    ]
