# Generated by Django 2.2.1 on 2019-05-29 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_call_url', models.URLField(verbose_name='Data source url')),
                ('subscriber', models.CharField(blank=True, max_length=11, null=True, verbose_name='Call Source')),
                ('destination', models.CharField(blank=True, max_length=11, null=True, verbose_name='Call Destination')),
                ('start_timestamp', models.DateTimeField(verbose_name='Start time of the call')),
                ('stop_timestamp', models.DateTimeField(verbose_name='Stop time of the call')),
                ('call_duration', models.DurationField(verbose_name='Call Duration')),
                ('call_price', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Call Price')),
            ],
        ),
        migrations.AddIndex(
            model_name='bill',
            index=models.Index(fields=['subscriber'], name='bills_bill_subscri_bf781c_idx'),
        ),
    ]
