# Generated by Django 2.2.1 on 2019-05-31 15:09

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='bill',
            index=django.contrib.postgres.indexes.BrinIndex(fields=['stop_timestamp'], name='bills_bill_stop_ti_2e7a42_brin'),
        ),
    ]
